# frozen_string_literal: true

source "https://rubygems.org"
ruby '2.6.3'
group :test, :development do
  gem 'rspec'
  gem 'twilio-ruby'
end

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
