# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'rubocop', '~> 1.39'

gem 'rspec', '~> 3.12'

gem 'twilio-ruby', '~> 5.73'

gem 'dotenv', '~> 2.8'

gem "twilio_mock", "~> 0.4.6"
